// rcharts/src/components/BarChartExample.tsx

import { BarChart } from "@sisense/sdk-ui";
import { exampleData } from "./../models/exampleData";

export default function BarChartExample() {
  return (
    <BarChart dataSet={exampleData.data}
              dataOptions={{
                category: [exampleData.years],
                value: [exampleData.quantity, exampleData.units],
                breakBy: [],
              }}
    />
  );
}

// compose-sdk-app/src/app/bar-chart-example/bar-chart-example.component.ts
import { Component } from '@angular/core';
import { exampleData } from '../../example-data';

@Component({
  selector: 'app-bar-chart-example',
  templateUrl: './bar-chart-example.component.html',
  styleUrl: './bar-chart-example.component.css'
})
export class BarChartExampleComponent {
  dataSet = exampleData.data;
        dataOptions = {
            category: [exampleData.years],
            value: [exampleData.quantity, exampleData.units],
            breakBy: []
        };
}

<csdk-bar-chart [dataSet]="dataSet" [dataOptions]="dataOptions"/>
